[package]
name = "assettled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = { version = "0.3.9", features = ["serde"] }
thiserror = "1.0.30"
serde = { version = "1.0.136", features = ["derive"] }
toml = "0.5.8"
