[package]
name = "measurrred"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.5"
once_cell = "1.9.0"
usvg = "0.20.0"
resvg = "0.20.0"
tiny-skia = "0.6.2"
serde = { version = "1.0.133", features = ["derive"] }
quick-xml = { version = "0.22.0", features = ["serialize"] }

[dependencies.windows]
version = "0.30.0"
features = [
    "alloc",

    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",

    "build",
    "ApplicationModel_Activation",
    "Win32_System_Com",

    "Win32_System_LibraryLoader",
    "Win32_Graphics_Gdi",

    "Win32_System_Performance",
    "Win32_System_SystemInformation",
    "Win32_System_Power",
    "Win32_System_Diagnostics_Debug",
]

[build-dependencies]
embed-resource = "1.6.5"
