[workspace]
members = ["app", "assettled", "barious", "knowhw", "manualright", "renderrred"]

[profile.release]
panic = "abort"
lto = true

[profile.dev.package.resvg]
opt-level = 3

[profile.dev.package.usvg]
opt-level = 3

[profile.dev.package."tiny-skia"]
opt-level = 3
