[package]
name = "measurrred"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.5"
once_cell = "1.9.0"

[dependencies.windows]
version = "0.29.0"
features = [
    "alloc",

    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",

    "std",
    "build",
    "ApplicationModel_Activation",
    "Win32_System_Com",

    "Win32_System_LibraryLoader",
    "Win32_Graphics_Gdi",
]

[build-dependencies]
embed-resource = "1.6.5"
